version: '3.5'

services:
  postgres:
    container_name: mentor-session
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'mentor-session'
    ports:
      - 5433:5432
    volumes:
      - database:/var/lib/postgressql/data

  redis:
    image: redis/redis-stack:latest
    environment:
      REDIS_HOST: '127.0.0.1'
      REDIS_PASSWORD: 'tuan310779'
      REDIS_NAME: 'mentor-caching'
    ports:
      - '6378:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data
    command: redis-server --requirepass tuan310779

volumes:
  database:
    driver: local
  redis_data:
    driver: local
