version: '3.5'

services:
  postgres:
    container_name: mentor-session
    restart: unless-stopped
    image: postgres:15.3-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5433:5432
    volumes:
      - database:/var/lib/postgresql/data

  cache:
    image: redis/redis-stack:latest
    restart: always
    env_file: .env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_NAME: ${REDIS_NAME}
    ports:
      - '6378:6379'
      - '8001:8001'
    volumes:
      - cache:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  database:
    driver: local
  cache:
    driver: local
